services:
  - type: web
    name: wave-profile
    runtime: node
    buildCommand: npm install --omit=dev --no-fund --no-audit
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
